Task2. Try to extend classes.
11cfif/java-course pull request #2
Opened 2019-02-18 19:43 UTC by hBuzzy

2019-02-18 20:35 UTC, 11cfif requested changes

2019-02-18 20:35 UTC, 11cfif commented on .idea/dictionaries/nikba.xml
> +  <dictionary name="nikba" />
Не надо коммитить в центральный репозиторий файлы среды разработки

2019-02-18 20:35 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Task/Volumable.java
> +public interface Volumable {
В целом, не плохо, но на самом деле в коде много дублей. Подумайте про то, какие классы можно по логике выделить в иерархию, чтобы убрать дублирование

2019-02-18 20:50 UTC, hBuzzy commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Task/Volumable.java
> +public interface Volumable {
Рационально ли будет сделать отдельные классы, чтобы объединить в группы, к примеру:
объем + площадь 
Периметр + площадь

И наследовать уже их, а не отдельно Периметр, Объем в довесок к площади ?

2019-02-19 08:16 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Task/Volumable.java
> +public interface Volumable {
Ну в данный момент это не важно. В текущей задачи нет проблем, при изменении условий (или добавлении новых, возможно надо будет переделать, но это естественный процесс при программировании) Сейчас можно оставить 3 интерфейса

2019-02-19 12:50 UTC, 11cfif requested changes
На половину улучшили. Но дубли еще есть

2019-02-19 12:50 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Task/Rectangle.java
> +    double sideB;
давайте делать внутренние переменные, которые нигде не наследуюся - приватными. У нас же ООП, инкапсуляция, все дела

2019-03-02 23:50 UTC, closed without merging