SmolskiyFigure version 2.0
11cfif/java-course pull request #3
Opened 2019-02-18 19:43 UTC by smolskiy

2019-02-18 20:29 UTC, 11cfif requested changes

2019-02-18 20:29 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +    public static abstract class Sheep {
овечка?)

2019-02-18 20:29 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +    public class Square extends RectangularSheep implements Measurable2D {
в вашей иерархии что-то не так. Класс квадрат имеет три поля (не считая имени), использует из которых всего лишь одно.
В ООП почти всегда потомки - более сложные чем родители

2019-02-18 20:29 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        System.out.println("Периметр этой фигуры посчитать невозможно");
не надо делать такое поведение - поведением по умолчанию. Это исключение, сделайте такое поведение только у исключени

2019-02-18 20:33 UTC, smolskiy commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +    public static abstract class Sheep {
shape должно было быть :D

2019-02-19 08:20 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        public double sideA;
давайте без public переменных

2019-02-19 08:20 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        public double radius;
аналогично

2019-02-19 08:20 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        public double sideB;
public

2019-02-19 08:20 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        @java.lang.Override
тут что то не так

2019-02-19 08:25 UTC, smolskiy commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        @java.lang.Override
объем сферы 4/3 * Пи* r^3, в чем здесь ошибка?

2019-02-19 08:29 UTC, 11cfif requested changes

2019-02-19 08:29 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        @java.lang.Override
я про аннотацию

2019-02-19 08:29 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        @java.lang.Override
@java.lang.Override

2019-02-19 09:01 UTC, 11cfif requested changes
Проверьте область видимости во всех классах, где должны быть приватные поля, где нет

2019-02-19 09:01 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        private double sideA;
Смотрите, это поле не может быть приватным (так как оно используется наследниками) 
Сейчас у вас все работает, потому что вы пишите все в одном классе. А private - область видимости в рамках одного класса. Но если бы вы писали все в разных файлах идея бы показала ошибку.
P.S. одна из причин, почему в java используются внутренние классы, это как раз доступ к приватным полям основного класса, но в данной задаче нас интересует именно наследование, так что давайте без private и public

2019-02-19 09:05 UTC, smolskiy commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        private double sideA;
:D у меня просто не остается выбора) я не подумал что поля в родительских классах должны быть protected,сейчас все поправлю

2019-02-19 09:13 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        private double sideA;
Не, ну есть еще дэфолтный тип)

2019-02-19 09:15 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        protected String name;
Здесь в принципе не оязвтельно, потому что сейчас это поле нигде не используется. Обычно видимость увеличивают, в зависимости от потребности. Но ладно уже, засчитаю

2019-03-02 19:32 UTC, closed without merging