class(home) work
11cfif/java-course pull request #4
Opened 2019-03-02 16:01 UTC by polyblack

2019-03-02 19:28 UTC, 11cfif requested changes

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        throw new UnsupportedOperationException("Invalid operation for Ball.");
почему в интерфейсе есть что-то, про реализацию? Вообще не очень хорошо по дэфолту делать Unsupported, так как все фигуры, кроме шара поддерживают, но в любом случае интерфейс ничего не знает про шар

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Figure.java
> +    double a, b, c;
у любой фигуры есть три параметра a,b,c?

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Ball.java
> +    protected double radius;
получается, шар никак не использует три параметра фигуры? Так может с иерархией тогда что-то не так?

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Ball.java
> +    protected double radius;
думаю тут протектед не надо, протектед имеет смысл только тогда, когда переменная используется в наследнике.

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Circle.java
> +    protected double radius;
про а,б,с уже сказал, плюс подумайте над иерархией лучше. посмотрите где какие переменные используются и где есть копипаст

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/recSquare.java
> +public class recSquare extends Figure implements Measurable2D {
Название класса с большой буквы, если оно сосотит из двух слов,  то слова не сокращают

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Cube.java
> +    double a;
у вас есть такая переменная в классе фигуры, плохо дублировать названия переменных

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/recSquare.java
> +        return a*a;
вопрос на засыпку
RecSquare square = new RecSquare(10.0);
square.measure2D(); // что выведет?

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/strTriangle.java
> +    protected double a, b, c;
у вас есть эти переменные в классе фигуры

2019-03-02 19:28 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Figure.java
> +    double a, b, c;
и вот тут как раз желателен протектед, если хотите использовать эти переменные в наследниках

2019-03-04 19:28 UTC, polyblack commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/recSquare.java
> +        return a*a;
100.0?

2019-03-04 19:32 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/recSquare.java
> +        return a*a;
0. Потому что вы передали значение 10 в конструктор Фигуры, а в этом методе используется переменная квадрата (которая, условно, перетирает переменную из фигуры), а она у нас не инициализирована, таким образом переменная а в квадрате равна 0

2019-03-04 19:50 UTC, 11cfif requested changes
почти все хорошо.
Только еще перепроверьте формулы периметров и прочего, там много ошибок

2019-03-04 19:50 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/StraightTriangle.java
> +        super(a, b, c);
а зачем для прямоугольного треугольника 3 стороны? 2 стороны его однозначно задают

2019-03-04 19:50 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/ThreeVarFigure.java
> +public abstract class ThreeVarFigure {
этот класс не нужен

2019-03-04 19:50 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/TwoVarFigure.java
> +public abstract class TwoVarFigure {
подумайте, как можно слегка доработать иерархию этого класса

2019-03-06 06:51 UTC, alexanderGalkin11 requested changes

2019-03-06 06:51 UTC, alexanderGalkin11 commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Rectangle.java
> +        return a + b;
ну плохо вы поменяли формулы

2019-03-06 06:51 UTC, alexanderGalkin11 commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Square.java
> +        return a + a;
ну как так

2019-03-06 06:53 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Square.java
> +        return a + a;
не с того акка отписался, но суть не поменялась

2019-03-07 08:05 UTC, closed without merging