Modified task
11cfif/java-course pull request #6
Opened 2019-03-04 22:10 UTC by 6Naci

Пока мне не удалось ограничить некоторые методы от использования наследников (в частности периметр шара)

2019-03-04 22:14 UTC, 6Naci commented
Мне также не ясно, скорее всего из-за не внимательности, откуда взялись строки, первые 5-6 картинок

2019-03-06 07:05 UTC, 11cfif requested changes

2019-03-06 07:05 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +            return 0;
а почему тут 0?

2019-03-06 07:05 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +            return 0;
Периметра у шара не бывает, напишите тоже самое, что в интерфейсе Iterator в методе remove:
Киньте искючение, что этот метод не поддерживается для данного объекта

2019-03-06 07:05 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +        Circle(int r) {
сделайте все конструкторы публичными, чтобы можно было их создать из вне пакета

2019-03-06 07:06 UTC, 11cfif commented
> Мне также не ясно, скорее всего из-за не внимательности, откуда взялись строки, первые 5-6 картинок

картинок? Я не понял проблемы

2019-03-06 07:36 UTC, 6Naci commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +            return 0;
Александр Сергеевич, есть источник, который Вы могли бы посоветовать на счет этой темы?

2019-03-06 08:32 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +            return 0;
Про исключения я поговорю на следующих лекциях. Пока можете просто скопировать код из класса Iterator. Для того чтобы найти класс, нажмите в среде ctrl + n и просто пишите название класса.

2019-03-06 09:02 UTC, 6Naci commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +            return 0;
Спасибо, нашёл, что необходимо и отправил исправленный вариант

2019-03-06 09:04 UTC, 11cfif commented on src/main/java/ru/spsuace/course/lesson2/classwork/classes/work/Measurable2D.java
> +            return 0;
я зачел уже :)

2019-03-06 19:00 UTC, closed without merging